# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/node:7.10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test:ci

      # deployment
      - run: bash .circleci/setup-droplet.sh
      - add_ssh_keys:
          fingerprints:
            - "b7:97:e8:eb:da:e0:49:1e:2b:c2:5a:ea:79:3f:07:65"
      - deploy:
          name: Deploy master to Digital Ocean
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -v ${DROPLET} "cd ${PROJECT_FOLDER};"
              git checkout master
              git pull
            else
              echo "Not master branch so not deploying"
            fi
