# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/node:7.10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test:ci
      - deploy:
  master:
    name: Deploy master to Digital Ocean
    command: |
      if [ "${CIRCLE_BRANCH}" == "master" ]; then
        ssh -v akallabeth@178.52.69.76 "cd ~/DataStructuresJs; ./circle_deployer.sh"
      else
        echo "Not master branch so not deploying"
      fi
